require 'AdventOfCode2021/version'
require 'AdventOfCode2021/submarine'
require 'AdventOfCode2021/submarine_depths'
require 'AdventOfCode2021/submarine_diagnostic'
require 'AdventOfCode2021/submarine_bingo'
require 'AdventOfCode2021/hydrothermal_vents'
require 'AdventOfCode2021/lanternfish'
